# add code or code the file to alacritty folder in your .config folder
# if you do not have the folder for alacritty you can simply create the dir
# font for powerleve10k 
# powerlevel0k github https://github.com/romkatv/powerlevel10k

# to install font yay -S ttf-meslo-nerd-font-powerlevel10k

[font.normal]
family = "MesloLGS NF"

# window transparency
[window]
opacity = 0.9

# Default colors
[colors.primary]
background = '#000000'
foreground = '#b6b6b6'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#990000'
green   = '#00a600'
yellow  = '#999900'
blue    = '#0000b2'
magenta = '#b200b2'
cyan    = '#00a6b2'
white   = '#bfbfbf'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#e50000'
green   = '#00d900'
yellow  = '#e5e500'
blue    = '#0000ff'
magenta = '#e500e5'
cyan    = '#00e5e5'
white   = '#e5e5e5'
